version: '3'

services:
  ide-server:
    build:
      context: ./ide-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ide-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    restart: unless-stopped

  mediasoup-server:
    build:
      context: ./mediasoup-server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
      - "40000-49999:40000-49999/udp"
    volumes:
      - ./mediasoup-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MEDIASOUP_PORT=3030
      - MEDIASOUP_ANNOUNCED_IP=127.0.0.1
      - MEDIASOUP_LISTEN_IP=0.0.0.0
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_SERVER_URL=http://localhost:5000
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_MEDIASOUP_SERVER_URL=http://localhost:3030
    depends_on:
      - ide-server
      - mediasoup-server
    restart: unless-stopped 